name: Build library

on:
  workflow_call:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make libubloxcfg.so
    - name: install library
      run: sudo make install-library
